name: Pytest on Multiple OS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 pytest-windows-on-arm:
    name: Pytest on Windows on ARM
    runs-on: windows-11-arm
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install Visual Studio C++ Build Tools (ARM64)
      run: |
        curl -LO https://aka.ms/vs/17/release/vs_BuildTools.exe
        Start-Process -FilePath .\vs_BuildTools.exe -ArgumentList `
          '--quiet', '--wait', '--norestart', `
          '--nocache', `
          '--add', 'Microsoft.VisualStudio.Component.VC.Tools.ARM64', `
          '--add', 'Microsoft.VisualStudio.Workload.VCTools', `
          '--installPath', 'C:\BuildTools' `
          -NoNewWindow -Wait
    - name: Add cl.exe to PATH (if needed)
      run: |
        $vsPath = "C:\BuildTools\VC\Tools\MSVC"
        $versionDir = Get-ChildItem $vsPath | Sort-Object Name -Descending | Select-Object -First 1
        $binPath = Join-Path $versionDir.FullName "bin\Hostx64\arm64"
        $env:PATH += ";$binPath"
    - name: Install Rust and Cargo for ARM64
      run: |
        curl -sSL -o rustup-init.exe https://static.rust-lang.org/rustup/dist/aarch64-pc-windows-msvc/rustup-init.exe
        ./rustup-init.exe -y --default-toolchain stable --profile minimal
        $env:PATH += ";$env:USERPROFILE\.cargo\bin"
    - name: Install dependencies with debug output
      run: |
        python -m pip install --upgrade pip
        pip install --verbose --progress-bar=off cython pytest
        if (Test-Path requirements.txt) { pip install --verbose --progress-bar=off -r requirements.txt }
    - name: Compile Cython code
      run: |
        python src/setup.py build_ext --inplace
    - name: List files in /build
      run: |
        dir /build
