name: Test on Windows ARM64

on: [push, pull_request]

jobs:
  test-windows-arm64:
    name: Test on Windows ARM64
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Download cryptography wheel artifact (manual URL)
        run: |
          Invoke-WebRequest -Uri "https://github.com/rsilva48/ARMDEPTEST/actions/runs/15278442163/artifacts/3204920320" -OutFile cryptography-wheel-arm64.zip
          Expand-Archive -Path cryptography-wheel-arm64.zip -DestinationPath wheelhouse

      - name: List files in wheelhouse before install
        run: |
          dir wheelhouse

      - name: Download and extract ARM64 wheels pack (Gohlke)
        run: |
          Invoke-WebRequest -Uri "https://github.com/cgohlke/win_arm64-wheels/releases/download/v2025.3.31/2025.3.31-experimental-cp313-win_arm64.whl.zip" -OutFile wheels-arm64.zip
          Expand-Archive -Path wheels-arm64.zip -DestinationPath wheels-arm64

      - name: List all files in wheels-arm64 recursively
        run: |
          Get-ChildItem -Path wheels-arm64 -Recurse

      - name: Install ARM64 wheels from pack
        run: |
          pip install wheels-arm64/bcrypt-4.3.0-cp313-cp313-win_arm64.whl
          pip install wheels-arm64/cffi-1.17.1-cp313-cp313-win_arm64.whl
          pip install wheels-arm64/greenlet-3.1.1-cp313-cp313-win_arm64.whl
          pip install wheels-arm64/numpy-2.2.4-cp313-cp313-win_arm64.whl
          pip install wheels-arm64/pandas-2.2.3-cp313-cp313-win_arm64.whl
          pip install wheels-arm64/pyodbc-5.2.0-cp313-cp313-win_arm64.whl
          pip install wheels-arm64/SQLAlchemy-2.0.40-cp313-cp313-win_arm64.whl

      - name: Install cryptography wheel and other dependencies
        run: |
          pip install --upgrade pip
          pip install $(Resolve-Path wheelhouse/cryptography*.whl)
          if (Test-Path requirements.txt) { pip install -r requirements.txt }

      - name: Compile Cython code
        run: |
          python src/setup.py build_ext --inplace

      - name: Run Pytest
        run: |
          pytest tests/

      - name: List files in /build
        run: |
          dir /build
